### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by its-dibo** [coveo/semantic-monorepo-tools#145]
we need clearer docs, how exactly it works, and how to configure it.
[this example](https://github.com/coveo/semantic-monorepo-tools/blob/HEAD/scripts/release.mjs) doesn't tell us much info about every thing

**Comment by louis-bompart** [comment]
Hey @its-dibo, indeed the documentation of the project is very lean, mainly because the project is lean: it's just a collection of JavaScript/TypeScript functions on top of various programs such as git or npm. As such, there's no need for special configuration, and so there's no really a need to document "how to configure it" I think because there's no configuration specific to this library.

If you have a precise point you'd like to see improve, don't hesitate to share it with us here, or to open a Pull Request.
